In [6]:
import pandas as pd
import openpyxl

In [20]:
#Pulling the Excel File & Sheet
path = "../STATS/all_stars_2018/test.xlsx"
stats_df = pd.read_excel(path, sheet_name="Lineups", engine="openpyxl")

/Users/jenniferdean/opt/anaconda3/lib/python3.8/site-packages/openpyxl/worksheet/_reader.py:300: UserWarning: Conditional Formatting extension is not supported and will be removed
  warn(msg)
/Users/jenniferdean/opt/anaconda3/lib/python3.8/site-packages/openpyxl/worksheet/_reader.py:300: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [21]:
#Check that the data came through
stats_df.head()

,Gotham Girls Roller Derby / All-Stars,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Black,Unnamed: 8,Unnamed: 9,...,None.15,None.16,None.17,None.18,None.19,None.20,None.21,None.22,None.23,1.1
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Color,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GAME 1
1,Jam,noPivot,Jammer,Box,NaN,NaN,Pivot,Box,NaN,NaN,...,NaN,NaN,Blocker,Box,NaN,NaN,NaN,Team Roster,NaN,NaN
2,1,NaN,1706,NaN,NaN,NaN,23,NaN,NaN,NaN,...,NaN,NaN,9,NaN,NaN,NaN,0.0,NaN,77.0,Mad Dog Murph
3,2,NaN,010,NaN,NaN,NaN,1680,NaN,NaN,NaN,...,NaN,NaN,62,NaN,NaN,NaN,0.0,NaN,NaN,NaN
4,3,NaN,1706,NaN,NaN,NaN,23,NaN,NaN,NaN,...,NaN,NaN,912,NaN,NaN,NaN,0.0,NaN,111.0,Jamsterella

In [22]:
stats_df = stats_df.fillna(0)
stats_df = stats_df.drop([0], axis = "index")
stats_df = stats_df.reset_index()
stats_df.head()

,index,Gotham Girls Roller Derby / All-Stars,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Black,Unnamed: 8,...,None.15,None.16,None.17,None.18,None.19,None.20,None.21,None.22,None.23,1.1
0,1,Jam,noPivot,Jammer,Box,0,0.0,Pivot,Box,0.0,...,0.0,0.0,Blocker,Box,0.0,0.0,0.0,Team Roster,0.0,0
1,2,1,0,1706,0,0,0.0,23,0,0.0,...,0.0,0.0,9,0,0.0,0.0,0.0,0,77.0,Mad Dog Murph
2,3,2,0,010,0,0,0.0,1680,0,0.0,...,0.0,0.0,62,0,0.0,0.0,0.0,0,0.0,0
3,4,3,0,1706,0,0,0.0,23,0,0.0,...,0.0,0.0,912,0,0.0,0.0,0.0,0,111.0,Jamsterella
4,5,4,0,1978,0,0,0.0,23,$,0.0,...,0.0,0.0,912,0,0.0,0.0,0.0,0,0.0,0

In [23]:
stats_df = stats_df.rename(columns=stats_df.iloc[0]).drop(stats_df.index[0])
stats_df = stats_df.drop([1, "noPivot", "Box", 0.0, 0, "Team Roster"], axis = 1)
stats_df.head()

,Jam,Jammer,Pivot,Blocker,Blocker,Blocker,Jam,Jammer,Pivot,Blocker,Blocker,Blocker
1,1,1706,23,17,314,68,1,480,301,912,950,9
2,2,010,1680,41,4500,4,2,814,21,235,82,62
3,3,1706,23,17,314,68,3,6,301,9,950,912
4,4,1978,23,17,4,41,4,111,21,235,62,912
5,5,010,17,314,213,68,5,111,301,235,912,9

In [25]:
stats_df.columns = ["jam_number",
                    "home_jammer_number",
                    "home_pivot_number",
                    "home_blocker_1_number",
                    "home_blocker_2_number",
                    "home_blocker_3_number",
                    "redundant",
                    "away_jammer_number",
                    "away_pivot_number",
                    "away_blocker_1_number",
                    "away_blocker_2_number",
                    "away_blocker_3_number"]

stats_df = stats_df.drop(["redundant"], axis = 1)
stats_df.head()

,jam_number,home_jammer_number,home_pivot_number,home_blocker_1_number,home_blocker_2_number,home_blocker_3_number,away_jammer_number,away_pivot_number,away_blocker_1_number,away_blocker_2_number,away_blocker_3_number
1,1,1706,23,17,314,68,480,301,912,950,9
2,2,010,1680,41,4500,4,814,21,235,82,62
3,3,1706,23,17,314,68,6,301,9,950,912
4,4,1978,23,17,4,41,111,21,235,62,912
5,5,010,17,314,213,68,111,301,235,912,9
...,...,...,...,...,...,...,...,...,...,...,...
77,0,0,0,0,0,0,0,0,0,0,0
78,0,0,0,0,0,0,0,0,0,0,0
79,0,0,0,0,0,0,0,0,0,0,0
80,0,0,0,0,0,0,0,0,0,0,0
81,/ = entered in this jam. X = finished service...,0,0,0,0,0,0,0,0,0,0

In [35]:
#period_one_df
period_one_lineups_df = stats_df[0:38]
period_one_lineups_df

,jam_number,home_jammer_number,home_pivot_number,home_blocker_1_number,home_blocker_2_number,home_blocker_3_number,away_jammer_number,away_pivot_number,away_blocker_1_number,away_blocker_2_number,away_blocker_3_number
1,1,1706,23,17,314,68,480,301,912,950,9
2,2,010,1680,41,4500,4,814,21,235,82,62
3,3,1706,23,17,314,68,6,301,9,950,912
4,4,1978,23,17,4,41,111,21,235,62,912
5,5,010,17,314,213,68,111,301,235,912,9
6,6,56,1680,4500,41,4,480,301,21,235,62
7,7,1706,17,68,41,314,814,301,912,9,62
8,8,1978,32,4500,41,4,6,21,27,62,82
9,9,1706,17,314,68,23,111,301,950,912,9
10,10,010,1680,4500,4,41,480,301,21,62,235
11,11,56,17,314,213,68,814,301,9,912,235
12,12,1978,32,4,41,4500,6,21,62,912,235
13,13,1706,23,17,68,314,480,301,9,912,235
14,14,010,1680,4,41,4500,814,21,62,82,077
15,15,1706,17,4,68,314,6,301,912,9,950
16,16,1978,32,4500,4,41,111,21,82,235,62
17,17,56,23,68,314,17,480,21,912,301,9
18,18,010,1680,4,41,4500,814,21,82,235,62
19,19,1706,23,17,314,68,6,301,950,912,9
20,20,1978,32,41,4,4500,111,21,235,62,82
21,21,1978,17,68,314,213,480,301,950,912,9
22,22,010,1680,4500,4,41,814,21,62,912,235
23,0,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,0
30,0,0,0,0,0,0,0,0,0,0,0
31,0,0,0,0,0,0,0,0,0,0,0
32,0,0,0,0,0,0,0,0,0,0,0
33,0,0,0,0,0,0,0,0,0,0,0
34,0,0,0,0,0,0,0,0,0,0,0
35,0,0,0,0,0,0,0,0,0,0,0
36,0,0,0,0,0,0,0,0,0,0,0
37,0,0,0,0,0,0,0,0,0,0,0
38,0,0,0,0,0,0,0,0,0,0,0

In [37]:
#period_two_df
period_two_lineups_df = stats_df[42:80]
period_two_lineups_df

,jam_number,home_jammer_number,home_pivot_number,home_blocker_1_number,home_blocker_2_number,home_blocker_3_number,away_jammer_number,away_pivot_number,away_blocker_1_number,away_blocker_2_number,away_blocker_3_number
43,1,1706,1680,17,314,68,480,301,912,9,950
44,2,010,4500,41,314,4,814,21,62,82,235
45,3,1706,4500,17,314,68,6,301,950,912,9
46,4,1978,32,4,41,4500,111,21,62,235,82
47,5,56,23,17,68,314,480,301,912,950,9
48,6,010,23,4,4500,41,814,21,235,950,9
49,7,1706,23,314,17,68,6,21,912,950,301
50,8,1978,32,4,41,4500,6,21,235,62,82
51,9,010,23,17,68,314,111,301,912,950,9
52,10,010,1680,4,41,4500,480,21,235,82,62
53,11,56,1680,17,314,68,814,301,912,950,9
54,12,1706,1680,4,41,4500,6,21,62,82,235
55,13,1978,23,17,68,314,111,301,9,950,912
56,14,010,32,4,41,4500,480,21,62,82,235
57,15,1706,17,68,314,4500,814,301,9,912,950
58,16,56,4500,68,4,41,6,21,62,077,235
59,17,1978,23,17,314,68,111,912,9,077,235
60,18,010,4500,17,41,4,480,21,62,077,235
61,19,1706,23,314,68,17,814,301,9,950,912
62,20,56,4500,4,68,41,6,21,62,235,82
63,21,010,23,68,314,17,111,21,62,9,912
64,22,010,32,4,41,4500,480,21,62,235,82
65,23,1706,23,17,68,314,111,21,62,235,82
66,0,0,0,0,0,0,0,0,0,0,0
67,0,0,0,0,0,0,0,0,0,0,0
68,0,0,0,0,0,0,0,0,0,0,0
69,0,0,0,0,0,0,0,0,0,0,0
70,0,0,0,0,0,0,0,0,0,0,0
71,0,0,0,0,0,0,0,0,0,0,0
72,0,0,0,0,0,0,0,0,0,0,0
73,0,0,0,0,0,0,0,0,0,0,0
74,0,0,0,0,0,0,0,0,0,0,0
75,0,0,0,0,0,0,0,0,0,0,0
76,0,0,0,0,0,0,0,0,0,0,0
77,0,0,0,0,0,0,0,0,0,0,0
78,0,0,0,0,0,0,0,0,0,0,0
79,0,0,0,0,0,0,0,0,0,0,0
80,0,0,0,0,0,0,0,0,0,0,0