In [1]:
import pandas as pd
import openpyxl

In [2]:
#Pulling the Excel File & Sheet
path = "STATS/all_stars_2018/test.xlsx"
stats_df = pd.read_excel(path, sheet_name="SK", engine="openpyxl")

/Users/jenniferdean/opt/anaconda3/lib/python3.8/site-packages/openpyxl/worksheet/_reader.py:300: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [3]:
#Check that the data came through
stats_df

,Per 1,Home,2,17,Unnamed: 4,Unnamed: 5,3,4,Unnamed: 8,5,...,Unnamed: 21,22,23,Unnamed: 24,24,25,26,38,Unnamed: 29,Unnamed: 30
0,Jam #,Jam Row,Jammer,Points,Team Pts,+/-,Lost,Lead,Lead +/-,Call,...,+/-,Lost,Lead,Lead +/-,Call,Inj,NI,Trips,Time,Pts / Min
1,1,4,1706,3,3,3,NaN,1,3,1,...,-3,NaN,NaN,NaN,NaN,NaN,NaN,1,0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,5,010,2,2,2,NaN,1,2,1,...,-2,NaN,NaN,NaN,NaN,NaN,NaN,1,0,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,NaN,NaN,Per 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
226,NaN,NaN,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
227,20,NaN,Per 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
228,NaN,NaN,Per 2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229,NaN,NaN,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Drop all NA columns & Rows // Reset the header of the dataframe
stats_df = stats_df.dropna(axis=1, how="all")
stats_df = stats_df.dropna(axis="index", how="all").reset_index()
stats_df = stats_df = stats_df.rename(columns=stats_df.iloc[0]).drop(stats_df.index[0])
stats_df

,0,Jam #,Jam Row,Jammer,Points,Team Pts,+/-,Lost,Lead,Lead +/-,...,+/-,Lost,Lead,Lead +/-,Call,Inj,NI,Trips,Time,Pts / Min
1,1,1,4,1706,3,3,3,NaN,1,3,...,-3,NaN,NaN,NaN,NaN,NaN,NaN,1,0,NaN
2,3,2,5,010,2,2,2,NaN,1,2,...,-2,NaN,NaN,NaN,NaN,NaN,NaN,1,0,NaN
3,5,3,6,1706,4,4,4,NaN,1,4,...,-4,NaN,NaN,NaN,NaN,NaN,NaN,1,0,NaN
4,7,4,7,1978,4,4,4,NaN,1,4,...,-4,1,NaN,NaN,NaN,NaN,1,0,0,NaN
5,9,5,8,010,0,0,-13,1,NaN,NaN,...,13,NaN,1,13,1,NaN,NaN,3,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,225,NaN,NaN,Per 2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140,226,NaN,NaN,Total,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
141,227,20,NaN,Per 1,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142,228,NaN,NaN,Per 2,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143,229,NaN,NaN,Total,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
stats_df = stats_df.drop([0], axis = 1)
stats_df.columns = ["jam_number",
                               "not_needed",
                                "home_jammer_number",
                                "home_points_scored",
                                "not_needed",
                                "home_differential",
                                "home_lost_lead",
                                "home_gained_lead",
                                "not_needed",
                                "home_called_off_jam",
                               "not_needed",
                               "not_needed",
                               "not_needed",
                               "not_needed",
                               "not_needed",
                               "not_needed",
                               "not_needed",
                               "away_jammer_number",
                                "away_points_scored",
                                "not_needed",
                                "away_differential",
                                "away_lost_lead",
                                "away_gained_lead",
                                "not_needed",
                                "away_called_off_jam",
                               "not_needed",
                               "not_needed",
                               "not_needed",
                               "not_needed",
                              "not_needed"]

stats_df  = stats_df.drop(["not_needed"], axis = 1)

stats_df

,jam_number,home_jammer_number,home_points_scored,home_differential,home_lost_lead,home_gained_lead,home_called_off_jam,away_jammer_number,away_points_scored,away_differential,away_lost_lead,away_gained_lead,away_called_off_jam
1,1,1706,3,3,NaN,1,1,480,0,-3,NaN,NaN,NaN
2,2,010,2,2,NaN,1,1,814,0,-2,NaN,NaN,NaN
3,3,1706,4,4,NaN,1,1,6,0,-4,NaN,NaN,NaN
4,4,1978,4,4,NaN,1,1,111,0,-4,1,NaN,NaN
5,5,010,0,-13,1,NaN,NaN,111,13,13,NaN,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,NaN,Per 2,NaN,NaN,NaN,NaN,NaN,Per 2,NaN,NaN,NaN,NaN,NaN
140,NaN,Total,NaN,NaN,NaN,NaN,NaN,Total,NaN,NaN,NaN,NaN,NaN
141,20,Per 1,NaN,NaN,NaN,NaN,NaN,Per 1,NaN,NaN,NaN,NaN,NaN
142,NaN,Per 2,NaN,NaN,NaN,NaN,NaN,Per 2,NaN,NaN,NaN,NaN,NaN
143,NaN,Total,NaN,NaN,NaN,NaN,NaN,Total,NaN,NaN,NaN,NaN,NaN

In [8]:
stats_df = stats_df.fillna("0")
stats_df = stats_df.reset_index(drop=True)
stats_df

,jam_number,home_jammer_number,home_points_scored,home_differential,home_lost_lead,home_gained_lead,home_called_off_jam,away_jammer_number,away_points_scored,away_differential,away_lost_lead,away_gained_lead,away_called_off_jam
0,1,1706,3,3,0,1,1,480,0,-3,0,0,0
1,2,010,2,2,0,1,1,814,0,-2,0,0,0
2,3,1706,4,4,0,1,1,6,0,-4,0,0,0
3,4,1978,4,4,0,1,1,111,0,-4,1,0,0
4,5,010,0,-13,1,0,0,111,13,13,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,0,Per 2,0,0,0,0,0,Per 2,0,0,0,0,0
139,0,Total,0,0,0,0,0,Total,0,0,0,0,0
140,20,Per 1,0,0,0,0,0,Per 1,0,0,0,0,0
141,0,Per 2,0,0,0,0,0,Per 2,0,0,0,0,0
142,0,Total,0,0,0,0,0,Total,0,0,0,0,0

In [13]:
#Set two dataframes with the different periods
period_one_stats_df = stats_df[:38]
period_two_stats_df = stats_df[42:80].reset_index(drop=True)

In [16]:
period_two_stats_df

,jam_number,home_jammer_number,home_points_scored,home_differential,home_lost_lead,home_gained_lead,home_called_off_jam,away_jammer_number,away_points_scored,away_differential,away_lost_lead,away_gained_lead,away_called_off_jam
0,1,1706,14,14,0,1,1,480,0,-14,0,0,0
1,2,010,0,-3,0,0,0,814,3,3,0,1,1
2,3,1706,0,-11,0,0,0,6,11,11,0,1,1
3,4,1978,0,-2,0,0,0,111,2,2,0,1,1
4,5,56,0,-5,0,0,0,480,5,5,0,1,1
5,6,010,16,16,0,1,1,814,0,-16,0,0,0
6,7,1706,4,4,0,1,0,6,0,-4,1,0,0
7,8,1978,4,4,0,1,1,6,0,-4,0,0,0
8,9,010,0,-20,1,0,0,111,20,20,0,1,1
9,10,010,15,15,0,1,1,480,0,-15,0,0,0
10,11,56,1,1,0,1,1,814,0,-1,0,0,0
11,12,1706,0,0,0,0,0,6,0,0,0,1,1
12,13,1978,3,-10,0,0,0,111,13,10,0,1,1
13,14,010,2,2,0,1,0,480,0,-2,0,0,0
14,15,1706,14,14,0,1,0,814,0,-14,0,0,0
15,16,56,10,10,0,1,1,6,0,-10,1,0,0
16,17,1978,4,4,0,1,1,111,0,-4,0,0,0
17,18,010,0,0,0,0,0,480,0,0,0,1,1
18,19,1706,3,3,0,1,1,814,0,-3,0,0,0
19,20,56,5,5,0,1,0,6,0,-5,0,0,0
20,21,010,19,19,1,0,0,111,0,-19,1,0,0
21,22,010,0,-4,0,0,0,480,4,4,0,1,1
22,23,1706,9,9,0,1,1,111,0,-9,0,0,0
23,24,0,0,0,0,0,0,0,0,0,0,0,0
24,25,0,0,0,0,0,0,0,0,0,0,0,0
25,26,0,0,0,0,0,0,0,0,0,0,0,0
26,27,0,0,0,0,0,0,0,0,0,0,0,0
27,28,0,0,0,0,0,0,0,0,0,0,0,0
28,29,0,0,0,0,0,0,0,0,0,0,0,0
29,30,0,0,0,0,0,0,0,0,0,0,0,0
30,31,0,0,0,0,0,0,0,0,0,0,0,0
31,32,0,0,0,0,0,0,0,0,0,0,0,0
32,33,0,0,0,0,0,0,0,0,0,0,0,0
33,34,0,0,0,0,0,0,0,0,0,0,0,0
34,35,0,0,0,0,0,0,0,0,0,0,0,0
35,36,0,0,0,0,0,0,0,0,0,0,0,0
36,37,0,0,0,0,0,0,0,0,0,0,0,0
37,38,0,0,0,0,0,0,0,0,0,0,0,0